apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messaging
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: default
  source:
    path: myapps/messaging
    repoURL: https://github.com/shichengshi/my-app-env.git
    targetRevision: HEAD