apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: shichengshi/my-airtng-node:1.0.0
        name: my-airtng-node
        imagePullPolicy: Always
        env:
        - name: DOCKER_MONGO
          value: backend.backend.svc:27017
        resources: {}
status: {}
